name: IPZS Sniper

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Avvia sniper
        run: python sniper_ipzs.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MTM_USERNAME: ${{ secrets.MTM_USERNAME }}
          MTM_PASSWORD: ${{ secrets.MTM_PASSWORD }}
          IPZS_USERNAME: ${{ secrets.IPZS_USERNAME }}
          IPZS_PASSWORD: ${{ secrets.IPZS_PASSWORD }}

      - name: Commit sniper_seen
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add sniper_seen.json
          git commit -m "update seen files" || echo "no changes"
          git push || echo "push fallito"
          git add cookies_ipzs.pkl
